#ifndef __KAD_EXCEPTIONS_H__
#define __KAD_EXCEPTIONS_H__

#include <stdexcept>

/** Base class for all the exceptions generated by QuadIron. */
class KadException : public std::runtime_error {
  public:
    explicit KadException(const std::string& reason)
        : std::runtime_error(reason)
    {
    }
    explicit KadException(const char*& reason) : std::runtime_error(reason) {}
};

/** A faulty logic within the program (a programmer's mistake). */
class KadLogicError : public KadException {
  public:
    explicit KadLogicError(const std::string& reason) : KadException(reason) {}
    explicit KadLogicError(const char* reason) : KadException(reason) {}
};

/** A domain error. */
class KadDomainError : public KadException {
  public:
    explicit KadDomainError(const std::string& reason) : KadException(reason) {}
    explicit KadDomainError(const char* reason) : KadException(reason) {}
};

#endif
