#ifndef __KAD_EXCEPTIONS_H__
#define __KAD_EXCEPTIONS_H__

#include <stdexcept>

namespace kad {

/** Base class for all the exceptions generated by QuadIron. */
class Exception : public std::runtime_error {
  public:
    explicit Exception(const std::string& reason) : std::runtime_error(reason)
    {
    }
    explicit Exception(const char*& reason) : std::runtime_error(reason) {}
};

/** A faulty logic within the program (a programmer's mistake). */
class LogicError : public Exception {
  public:
    explicit LogicError(const std::string& reason) : Exception(reason) {}
    explicit LogicError(const char* reason) : Exception(reason) {}
};

/** A domain error. */
class DomainError : public Exception {
  public:
    explicit DomainError(const std::string& reason) : Exception(reason) {}
    explicit DomainError(const char* reason) : Exception(reason) {}
};

} // namespace kad

#endif
